version: 2

models:
  - name: dim_customers
    description: This table has basic information about a customer, as well as some derived facts based on a customer's orders

    columns:
      - name: customer_id
        description: This is a unique identifier for a customer
        tests:
          - unique
          - not_null
        meta:
          metrics:
            unique_customer_count:
              type: count_distinct
      - name: first_name
        description: Customer's first name. PII.
      - name: last_name
        description: Customer's last name. PII.
      - name: created
        description: Timestamp (UTC) when customer was created
        meta:
          metrics:
            date_of_first_created_customer:
              type: min
            date_of_most_recent_created_customer:
              type: max
      - name: first_order
        description: Date of the customers first order
      - name: most_recent_order
        description: Date of the customers most recent order
      - name: number_of_orders
        description: Total number orders made by the customer
      - name: customer_lifetime_value
        description: Total amound spent by customer since first purchase.


  # - name: orders
  #   description: This table has basic information about orders, as well as some derived facts based on payments

  #   meta:
  #     joins:
  #       - join: customers
  #         sql_on: ${customers.customer_id} = ${orders.customer_id}


  #   columns:
  #     - name: order_id
  #       tests:
  #         - unique
  #         - not_null
  #       description: This is a unique identifier for an order
  #       meta:
  #         metrics:
  #           unique_order_count:
  #             type: count_distinct

  #     - name: is_completed
  #       description: Boolean indicating if status is completed

  #     - name: customer_id
  #       description: Foreign key to the customers table
  #       tests:
  #         - not_null
  #         - relationships:
  #             to: ref('customers')
  #             field: customer_id

  #     - name: order_date
  #       description: Date (UTC) that the order was placed
  #       meta:
  #         metrics:
  #           date_of_first_order:
  #             type: min
  #           date_of_most_recent_order:
  #             type: max

  #     - name: status
  #       description: '{{ doc("orders_status") }}'
  #       tests:
  #         - accepted_values:
  #             values: ['placed', 'shipped', 'completed', 'return_pending', 'returned']

  #     - name: amount
  #       description: Total amount (AUD) of the order
  #       tests:
  #         - not_null
  #       meta:
  #         metrics:
  #           avg_amount:
  #             type: average

  #     - name: credit_card_amount
  #       description: Amount of the order (AUD) paid for by credit card
  #       tests:
  #         - not_null

  #     - name: coupon_amount
  #       description: Amount of the order (AUD) paid for by coupon
  #       tests:
  #         - not_null

  #     - name: bank_transfer_amount
  #       description: Amount of the order (AUD) paid for by bank transfer
  #       tests:
  #         - not_null

  #     - name: gift_card_amount
  #       description: Amount of the order (AUD) paid for by gift card
  #       tests:
  #         - not_null

  # - name: payments
  #   description: This table has information about individual payments

  #   meta:
  #     joins:
  #       - join: orders
  #         sql_on: ${orders.order_id} = ${payments.order_id}
  #       - join: customers
  #         sql_on: ${customers.customer_id} = ${orders.customer_id}

  #   columns:
  #     - name: payment_id
  #       description: This is a unique identifier for a payment
  #       meta:
  #         metrics:
  #           unique_payment_count:
  #             type: count_distinct
  #             description: count of all payments

  #     - name: order_id
  #       description: Foreign key to the orders table

  #     - name: payment_method
  #       description: Method of payment used, for example credit card

  #     - name: amount
  #       description: Total amount (AUD) of the individual payment
  #       meta:
  #         metrics:
  #           total_revenue:
  #             type: sum
  #             description: Sum of all payments